service: api-transacciones-abc
provider:
  name: aws
  runtime: python3.12
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${env:STAGE, 'dev'}
  iam:
    role: ${env:LAMBDA_IAM_ROLE_ARN}
  environment:
    TABLA_TRANSACCION: ${env:TABLA_TRANSACCION, 'TablaTransaccion'}
  httpApi:
    cors: true

functions:
  ImportComercios:
    handler: ImportComercios.lambda_handler
    events:
      - httpApi: { path: /import/comercios, method: POST }

  ImportTransacciones:
    handler: ImportTransacciones.lambda_handler
    events:
      - httpApi: { path: /import/transacciones, method: POST }

  BusquedaTransaccion:
    handler: BusquedaTransaccion.lambda_handler
    events:
      - httpApi: { path: /transacciones/buscar-por-id, method: GET }

  BusquedaCliente:
    handler: BusquedaCliente.lambda_handler
    events:
      - httpApi: { path: /transacciones/buscar-cliente, method: GET }

  BusquedaTarjeta:
    handler: BusquedaTarjeta.lambda_handler
    events:
      - httpApi: { path: /transacciones/buscar-tarjeta, method: GET }

  BusquedaComercio:
    handler: BusquedaComercio.lambda_handler
    events:
      - httpApi: { path: /transacciones/buscar-comercio, method: GET }
